Lesson 6: oauth with github and vk
geliadonchak/fefu_backend_3_6 pull request #6
Opened 2022-04-25 07:58 UTC by geliadonchak

2022-05-02 09:27 UTC, chrn-feip requested changes
Где реализация пункта 2.10 домашнего задания?

2022-05-02 09:27 UTC, chrn-feip commented on app/Http/Resources/UserResources.php
> +    #[ArrayShape(['name' => "mixed", 'email' => "mixed",
Это что такое? Код тестировался?

2022-05-02 09:27 UTC, chrn-feip commented on config/services.php
> +        'redirect' => 'http://localhost/oauth/github/login',
Это лучше не хардкодить. Сделайте:
- либо переменной в env (вариант не гибкий, по сути тот же хардкод, но не требует менять сам код),
- либо как я показывала в начале занятия 8 (провайдер-наследник + менеджер-наследник, позволяющие использовать route метод без хардкода домена и остальной части url).

2022-05-02 09:27 UTC, chrn-feip commented on resources/views/profile.blade.php
> +    <h3>Информация OAuth</h3>
Не нужно дублировать этот заголовок, он должен быть один. Далее список блоков соц. сетей с подзаголовком с названием сети и датами.

2022-05-02 10:28 UTC, geliadonchak commented on app/Http/Resources/UserResources.php
> +    #[ArrayShape(['name' => "mixed", 'email' => "mixed",
Да, тестировался. IDE показывала ворнинг, что можно добавить #[ArrayShape]

2022-05-02 12:09 UTC, chrn-feip requested changes

2022-05-02 12:09 UTC, chrn-feip commented on app/Http/Controllers/Web/AuthWebController.php
> +            $user->update();
Это не нужно

2022-05-05 03:22 UTC, chrn-feip requested changes

2022-05-05 03:22 UTC, chrn-feip commented on app/Http/Controllers/Web/AuthWebController.php
> -            $user->password = Hash::make($data['password']);;
Почему вы сочли этот код лишним? Из update и save был лишним только update. Всё остальное актуально. Ещ раз:
1. Получили запрос с данными на регистрацию, провалидировали
2. Выбрали пользователя по почте.
3. Если он есть, то установили ему пароль, даты логина и регистрации, сохранили.
4. Если его нет, создали из данных запроса.

Всё то же самое актуально так же и для регистрации через API. Это же один кусок бизнес-логики, который должен работать при двух способах взаимодействия с приложением

2022-05-05 03:38 UTC, chrn-feip commented
А в AuthApiController.php где изменения подобные?

2022-05-05 04:27 UTC, geliadonchak commented
Забыла в коммит файл добавить

2022-05-05 04:40 UTC, chrn-feip commented
> Забыла в коммит файл добавить

Всё ещё нет. Проверьте, не попал ли этот код в следующий PR.

2022-05-05 07:57 UTC, merged