Lesson 7: add categories
geliadonchak/fefu_backend_3_6 pull request #7
Opened 2022-05-04 09:50 UTC by geliadonchak

2022-05-04 09:54 UTC, geliadonchak commented
6 дз еще не проверили до конца, так что мердж, наверное, делать пока не надо, даже если все хорошо

2022-05-11 07:13 UTC, tonighty requested changes

2022-05-11 07:13 UTC, tonighty commented on app/Http/Controllers/Api/CatalogApiController.php
> +            ProductCategory::query()->paginate(5)
категориям пагинация не нужна

2022-05-11 07:13 UTC, tonighty commented on app/Policies/ProductCategoryPolicy.php
> +class ProductCategoryPolicy
эт не нужно

2022-05-11 07:13 UTC, tonighty commented on resources/views/catalog.blade.php
> +        @include('catalog_list', ['categories', $categories])
['categories' => $categories]

2022-05-12 14:49 UTC, tonighty approved these changes

2022-05-12 14:49 UTC, merged